name: local_secure_storage
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.1 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  flutter_secure_storage: ^7.0.1
  genius_api:
    path: ../genius_api
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  build_runner: ^2.4.13
 
