name: genius_wallet
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.18.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
  go_router: ^5.0.1
  flutter_bloc: ^8.1.1
  pin_code_fields: ^7.4.0
  flow_builder: ^0.0.9
  clipboard: ^0.1.3
  genius_api:
    path: packages/genius_api
  squidrouter:
    path: squidrouter
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.0
  url_launcher: ^6.1.6
  local_secure_storage:
    path: packages/local_secure_storage
  responsive_framework: ^0.2.0
  test: ^1.24.1
  ffi: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - packages/genius_wallet/assets/images/mask2.png
    - packages/genius_wallet/assets/images/mask4.png
    - packages/genius_wallet/assets/images/mask3.svg
    - packages/genius_wallet/assets/images/mask6.svg
    - packages/genius_wallet/assets/images/mask5.svg
    - packages/genius_wallet/assets/images/shape.svg
    - packages/genius_wallet/assets/images/mask3.png
    - packages/genius_wallet/assets/images/mask.svg
    - packages/genius_wallet/assets/images/optionscustom.png
    - packages/genius_wallet/assets/images/oval.png
    - packages/genius_wallet/assets/images/mask.png
    - packages/genius_wallet/assets/images/image1.png
    - packages/genius_wallet/assets/images/graphcustom.svg
    - packages/genius_wallet/assets/images/shape.png
    - packages/genius_wallet/assets/images/trendlinecustom.svg
    - packages/genius_wallet/assets/images/vector.svg
    - packages/genius_wallet/assets/images/ribookletfill.svg
    - packages/genius_wallet/assets/images/group18.svg
    - packages/genius_wallet/assets/images/bxsdashboard.svg
    - packages/genius_wallet/assets/images/checkmarksuffixicon.svg
    - packages/genius_wallet/assets/images/path4.svg
    - packages/genius_wallet/assets/images/combinedshape.png
    - packages/genius_wallet/assets/images/arrowtoggle.svg
    - packages/genius_wallet/assets/images/markettrendline.svg
    - packages/genius_wallet/assets/images/transactiontype.svg
    - packages/genius_wallet/assets/images/mask2.svg
    - packages/genius_wallet/assets/images/cointogglecustom.svg
    - packages/genius_wallet/assets/images/increasecustom.svg
    - packages/genius_wallet/assets/images/decreasecustom.svg
    - packages/genius_wallet/assets/images/transactionoptionscustom.svg
    - packages/genius_wallet/assets/images/transactiontypeiconcustom.svg
    - packages/genius_wallet/assets/images/mask4.svg
    - packages/genius_wallet/assets/images/chartoptionscustom.svg
    - packages/genius_wallet/assets/images/profileicon.png
    - packages/genius_wallet/assets/images/whitearrowleft.svg
    - packages/genius_wallet/assets/images/chatbubbles.png
    - packages/genius_wallet/assets/images/arrowselectorvertical3.png
    - packages/genius_wallet/assets/images/arrowselectorvertical2.png
    - packages/genius_wallet/assets/images/arrowselectorvertical.png
    - packages/genius_wallet/assets/images/vector4.svg
    - packages/genius_wallet/assets/images/whitearrowback.svg
    - packages/genius_wallet/assets/images/greenarrowright.svg
    - packages/genius_wallet/assets/images/line6.svg
    - packages/genius_wallet/assets/images/line7.svg
    - packages/genius_wallet/assets/images/line8.svg
    - packages/genius_wallet/assets/images/line9.svg
    - packages/genius_wallet/assets/images/line10.svg
    - packages/genius_wallet/assets/images/line11.svg
    - packages/genius_wallet/assets/images/ellipse1.png
    - packages/genius_wallet/assets/images/whitearrowright.svg
    - packages/genius_wallet/assets/images/walleticon.svg
    - packages/genius_wallet/assets/images/group.svg
    - packages/genius_wallet/assets/images/walletqrcode.svg
    - packages/genius_wallet/assets/images/statuslogo.svg
    - packages/genius_wallet/assets/images/ellipse17.png
    - packages/genius_wallet/assets/images/ellipse18.png
    - packages/genius_wallet/assets/images/ellipse19.png
    - packages/genius_wallet/assets/images/ellipse20.png
    - packages/genius_wallet/assets/images/ellipse21.png
    - packages/genius_wallet/assets/images/ellipse22.png
    - packages/genius_wallet/assets/images/copysymbol.svg
    - packages/genius_wallet/assets/images/shield_icon.png
    - packages/genius_wallet/assets/images/logo_and_title.png
    - packages/genius_wallet/assets/images/maskcurrencyselector.png
    - packages/genius_wallet/assets/images/passcodeframe.svg
    - packages/genius_wallet/assets/images/cancelledstatuslogo.svg
    - packages/genius_wallet/assets/images/masknextmonth.svg
    - packages/genius_wallet/assets/images/maskpreviousmonth.svg
    - packages/genius_wallet/assets/images/completedstatuslogo.svg
    - packages/genius_wallet/assets/images/maskarrow2.svg
    - packages/genius_wallet/assets/images/copywalletsymbol.svg
    - packages/genius_wallet/assets/images/pendingstatuslogo.svg
    - packages/genius_wallet/assets/images/maskarrow1.svg
    - packages/genius_wallet/assets/images/geniusappbarlogo.png
    - packages/genius_wallet/assets/images/coinicon.png
    - packages/genius_wallet/assets/images/ethereum_icon.png
    - packages/genius_wallet/assets/images/bitcoin_icon.png
    - packages/genius_wallet/assets/images/showmoreicon.png
    - packages/genius_wallet/assets/images/arrow.svg
    - packages/genius_wallet/assets/images/transactiontypearrow.svg
    - packages/genius_wallet/assets/images/walletqrcodecustom.svg
    - packages/genius_wallet/assets/images/copyicon.svg
    - packages/genius_wallet/assets/images/coinimage.png
    - packages/genius_wallet/assets/images/trendline.svg
    - packages/genius_wallet/assets/images/detailedtransactionoptionscustom.svg
    - packages/genius_wallet/assets/images/transactionarrow.svg
    - packages/genius_wallet/assets/images/coinicon.svg
    - packages/genius_wallet/assets/images/group3.svg
    - packages/genius_wallet/assets/images/group2.svg
    - packages/genius_wallet/assets/images/oval5.png
    - packages/genius_wallet/assets/images/oval45.svg
    - packages/genius_wallet/assets/images/path8.svg
    - packages/genius_wallet/assets/images/path2.svg
    - packages/genius_wallet/assets/images/path5.svg
    - packages/genius_wallet/assets/images/path10.svg
    - packages/genius_wallet/assets/images/navdashboardbuttoncustom.png
    - packages/genius_wallet/assets/images/navwalletbuttoncustom.png
    - packages/genius_wallet/assets/images/navstatsbuttoncustom.png
    - packages/genius_wallet/assets/images/navstatsbuttonactive.png
    - packages/genius_wallet/assets/images/navtimerbuttoncustom.png
    - packages/genius_wallet/assets/images/navtimerbuttonactive.png
    - packages/genius_wallet/assets/images/navcalculatorbuttoncustom.png
    - packages/genius_wallet/assets/images/navcalculatorbuttonactive.png
    - packages/genius_wallet/assets/images/navcalendarbuttoncustom.png
    - packages/genius_wallet/assets/images/navcalendarbuttonactive.png
    - packages/genius_wallet/assets/images/navwalletbuttoncustom2.png
    - packages/genius_wallet/assets/images/navnewsbuttoncustom.png
    - packages/genius_wallet/assets/images/navnewsbuttonactive.png
    - packages/genius_wallet/assets/images/combinedshape2.png
    - packages/genius_wallet/assets/images/navcalendarbuttoncustom.svg
    - packages/genius_wallet/assets/images/navcalculatorbuttoncustom.svg
    - packages/genius_wallet/assets/images/navnewsbuttoncustom.svg
    - packages/genius_wallet/assets/images/navtimerbuttoncustom.svg
    - packages/genius_wallet/assets/images/navstatsbuttoncustom.svg
    - packages/genius_wallet/assets/images/navwalletbuttoncustom.svg
    - packages/genius_wallet/assets/images/navwalletbuttonactive.png
    - packages/genius_wallet/assets/images/navdashboardbuttoncustom.svg
    - packages/genius_wallet/assets/images/navdashboardbuttonactive.png
    - packages/genius_wallet/assets/images/tradedesktopiconselected.svg
    - packages/genius_wallet/assets/images/tradedesktopiconunselected.svg
    - packages/genius_wallet/assets/images/desktoptradebuttonactive.svg
    - packages/genius_wallet/assets/images/arrowright.png
    - packages/genius_wallet/assets/images/arrowleft.png
