name: genius_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.5.0
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
    version: ^0.0.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  rxdart: ^0.27.7
  ffi: ^2.0.1
  secure_storage:
    path: ../secure_storage
  convert: ^3.1.1
  web3dart: ^2.7.3
  http: ^1.2.2
  path: ^1.9.0
